const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const db=window.KhoiDB?.client;
const state={events:[],bookings:[],spaces:[],popup:null,currentView:'dashboard'};

function toast(msg,type='ok'){const t=$('#toast');t.textContent=msg;t.className='toast show'+(type==='error'?' error':'');clearTimeout(toast._t);toast._t=setTimeout(()=>t.className='toast',2600)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function fmtDate(v){if(!v)return 'Sắp công bố';const d=new Date(v+'T00:00:00');return new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}
function fmtMoney(v,label){if(label)return label;if(!v)return 'Miễn phí';return new Intl.NumberFormat('vi-VN').format(v)+'đ/người'}
function fmtTime(t){return t?String(t).slice(0,5):''}
function statusLabel(s){return({published:'Đã ra mắt',coming_soon:'Coming soon',draft:'Bản nháp',new:'Mới',contacted:'Đã liên hệ',confirmed:'Đã xác nhận',cancelled:'Đã hủy'})[s]||s}
function safeLocalDateTime(v){if(!v)return '';const d=new Date(v);const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}

function setView(view){state.currentView=view;$$('.admin-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.admin-view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));const titles={dashboard:['KHÓI COFFEE','Tổng quan'],events:['QUẢN LÝ WEBSITE','Sự kiện'],bookings:['QUẢN LÝ WEBSITE','Booking phòng'],spaces:['QUẢN LÝ WEBSITE','Không gian quán'],popup:['QUẢN LÝ WEBSITE','Popup website']};$('#viewEyebrow').textContent=titles[view][0];$('#viewTitle').textContent=titles[view][1];$('.admin-sidebar').classList.remove('open')}
$$('.admin-nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.jump)));$('#mobileNavBtn').onclick=()=>$('.admin-sidebar').classList.toggle('open');

async function ensureAuth(){
  if(!window.KhoiDB?.ready){$('#loginMessage').textContent='Chưa cấu hình Supabase. Mở supabase-config.js và nhập URL + Publishable key.';return}
  const {data:{session}}=await db.auth.getSession();
  if(session){showApp(session.user);await loadAll()}else $('#authScreen').classList.remove('hidden');
}
function showApp(user){$('#authScreen').classList.add('hidden');$('#adminEmail').textContent=user?.email||''}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMessage').textContent='Đang đăng nhập...';const {data,error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){$('#loginMessage').textContent=error.message;return}$('#loginMessage').textContent='';showApp(data.user);await loadAll()});
$('#logoutBtn').onclick=async()=>{if(db)await db.auth.signOut();location.reload()};$('#refreshBtn').onclick=()=>loadAll(true);

async function loadAll(showToast=false){
  await Promise.all([loadEvents(),loadBookings(),loadSpaces(),loadPopup()]);renderDashboard();if(showToast)toast('Đã cập nhật dữ liệu');
}
async function loadEvents(){const {data,error}=await db.from('events').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error){toast('Không tải được sự kiện: '+error.message,'error');return}state.events=data||[];renderEvents()}
async function loadBookings(){const {data,error}=await db.from('room_bookings').select('*').order('created_at',{ascending:false});if(error){toast('Không tải được booking: '+error.message,'error');return}state.bookings=data||[];renderBookings()}
async function loadSpaces(){const {data,error}=await db.from('space_gallery').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:true});if(error){toast('Không tải được ảnh không gian: '+error.message,'error');return}state.spaces=data||[];renderSpaces()}
async function loadPopup(){const {data,error}=await db.from('site_popup').select('*').eq('id',1).maybeSingle();if(error){toast('Không tải được popup: '+error.message,'error');return}state.popup=data||{id:1,enabled:false};fillPopupForm()}

function renderDashboard(){const visible=state.events.filter(e=>e.status!=='draft').length,newB=state.bookings.filter(b=>b.status==='new').length;$('#statEvents').textContent=visible;$('#statBookings').textContent=newB;$('#statPopup').textContent=state.popup?.enabled?'Đang bật':'Đang tắt';$('#statPopup').style.fontSize='25px';
  $('#recentBookings').innerHTML=state.bookings.slice(0,5).map(b=>`<div class="recent-item"><div class="avatar">${esc((b.name||'?')[0]).toUpperCase()}</div><div><strong>${esc(b.name)}</strong><span>${esc(b.phone)} · ${fmtDate(b.booking_date)} ${fmtTime(b.booking_time)}</span></div><b>${statusLabel(b.status)}</b></div>`).join('')||'<p>Chưa có booking nào.</p>';
  $('#upcomingEvents').innerHTML=state.events.filter(e=>e.status!=='draft').slice(0,5).map(e=>`<div class="recent-item"><img src="${esc(e.image_url||'assets/cafe-05.jpg')}" alt=""><div><strong>${esc(e.title)}</strong><span>${e.status==='coming_soon'?'Coming soon':fmtDate(e.event_date)+' '+fmtTime(e.start_time)}</span></div><b>${fmtMoney(e.price,e.price_label)}</b></div>`).join('')||'<p>Chưa có sự kiện.</p>';
}

function filteredEvents(){const s=$('#eventSearch').value.trim().toLowerCase(),st=$('#eventStatusFilter').value;return state.events.filter(e=>(!s||e.title.toLowerCase().includes(s))&&(st==='all'||e.status===st))}
function renderEvents(){const list=filteredEvents();$('#adminEventsList').innerHTML=list.map(e=>`<article class="admin-event-card" data-edit-event="${e.id}"><img src="${esc(e.image_url||'assets/cafe-05.jpg')}" alt="${esc(e.title)}"><div class="admin-event-body"><div class="admin-event-top"><span>${esc(e.type||'EVENT')}</span><span class="status-pill status-${e.status}">${statusLabel(e.status)}</span></div><h3>${esc(e.title)}</h3><p>${e.status==='coming_soon'?'Chưa công bố lịch':fmtDate(e.event_date)+' · '+fmtTime(e.start_time)+(e.end_time?' — '+fmtTime(e.end_time):'')}</p><div class="admin-event-foot"><strong>${fmtMoney(e.price,e.price_label)}</strong><span>${e.featured?'★ Nổi bật':'Sửa →'}</span></div></div></article>`).join('')||'<div class="panel">Không tìm thấy sự kiện.</div>';$$('[data-edit-event]').forEach(c=>c.onclick=()=>openEventEditor(c.dataset.editEvent))}
$('#eventSearch').oninput=renderEvents;$('#eventStatusFilter').onchange=renderEvents;

function openEventEditor(id=null){const e=id?state.events.find(x=>x.id===id):null;$('#eventEditorTitle').textContent=e?'Chỉnh sự kiện':'Thêm sự kiện';$('#eventId').value=e?.id||'';$('#eventTitle').value=e?.title||'';$('#eventType').value=e?.type||'EVENT';$('#eventStatus').value=e?.status||'published';$('#eventDate').value=e?.event_date||'';$('#eventStart').value=fmtTime(e?.start_time);$('#eventEnd').value=fmtTime(e?.end_time);$('#eventPrice').value=e?.price??0;$('#eventPriceLabel').value=e?.price_label||'';$('#eventDesc').value=e?.description||'';$('#eventHighlights').value=(e?.highlights||[]).join('\n');$('#eventSort').value=e?.sort_order??100;$('#eventFeatured').checked=Boolean(e?.featured);$('#eventImageUrl').value=e?.image_url||'';$('#eventImagePreview').src=e?.image_url||'assets/cafe-05.jpg';$('#deleteEventBtn').style.visibility=e?'visible':'hidden';$('#eventEditorModal').classList.add('show')}
$('#addEventBtn').onclick=()=>openEventEditor();$$('[data-close-editor]').forEach(b=>b.onclick=()=>$('#eventEditorModal').classList.remove('show'));$('#eventImageUrl').oninput=()=>$('#eventImagePreview').src=$('#eventImageUrl').value||'assets/cafe-05.jpg';
async function uploadFile(file,prefix='events'){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${prefix}/${Date.now()}-${Math.random().toString(36).slice(2,8)}.${ext}`;const {error}=await db.storage.from('event-images').upload(path,file,{upsert:false});if(error)throw error;return db.storage.from('event-images').getPublicUrl(path).data.publicUrl}
$('#eventImageFile').onchange=e=>{const f=e.target.files?.[0];if(f)$('#eventImagePreview').src=URL.createObjectURL(f)};
$('#eventForm').addEventListener('submit',async ev=>{ev.preventDefault();try{let image=$('#eventImageUrl').value.trim();const file=$('#eventImageFile').files?.[0];if(file){toast('Đang upload ảnh...');image=await uploadFile(file);$('#eventImageUrl').value=image}const payload={title:$('#eventTitle').value.trim(),type:$('#eventType').value.trim()||'EVENT',status:$('#eventStatus').value,event_date:$('#eventDate').value||null,start_time:$('#eventStart').value||null,end_time:$('#eventEnd').value||null,price:Number($('#eventPrice').value||0),price_label:$('#eventPriceLabel').value.trim()||null,image_url:image||null,description:$('#eventDesc').value.trim(),highlights:$('#eventHighlights').value.split('\n').map(x=>x.trim()).filter(Boolean),sort_order:Number($('#eventSort').value||100),featured:$('#eventFeatured').checked,updated_at:new Date().toISOString()};const id=$('#eventId').value;const query=id?db.from('events').update(payload).eq('id',id):db.from('events').insert(payload);const {error}=await query;if(error)throw error;$('#eventEditorModal').classList.remove('show');toast(id?'Đã cập nhật sự kiện':'Đã tạo sự kiện');await loadEvents();renderDashboard()}catch(err){toast(err.message||'Có lỗi khi lưu','error')}});
$('#deleteEventBtn').onclick=async()=>{const id=$('#eventId').value;if(!id||!confirm('Xóa sự kiện này?'))return;const {error}=await db.from('events').delete().eq('id',id);if(error)return toast(error.message,'error');$('#eventEditorModal').classList.remove('show');toast('Đã xóa sự kiện');await loadEvents();renderDashboard()};

function filteredBookings(){const s=$('#bookingSearch').value.trim().toLowerCase(),st=$('#bookingStatusFilter').value;return state.bookings.filter(b=>(!s||(b.name||'').toLowerCase().includes(s)||(b.phone||'').toLowerCase().includes(s))&&(st==='all'||b.status===st))}
function renderBookings(){const list=filteredBookings();$('#bookingsTbody').innerHTML=list.map(b=>`<tr><td><strong>${esc(b.name)}</strong><small>${esc(b.phone)}</small></td><td><strong>${fmtDate(b.booking_date)}</strong><small>${fmtTime(b.booking_time)}</small></td><td>${b.people} người</td><td>${esc(b.duration)}</td><td>${esc(b.note||'—')}</td><td><select class="booking-status" data-booking-status="${b.id}"><option value="new" ${b.status==='new'?'selected':''}>Mới</option><option value="contacted" ${b.status==='contacted'?'selected':''}>Đã liên hệ</option><option value="confirmed" ${b.status==='confirmed'?'selected':''}>Đã xác nhận</option><option value="cancelled" ${b.status==='cancelled'?'selected':''}>Đã hủy</option></select></td></tr>`).join('')||'<tr><td colspan="6">Chưa có booking.</td></tr>';$$('[data-booking-status]').forEach(s=>s.onchange=async()=>{const {error}=await db.from('room_bookings').update({status:s.value}).eq('id',s.dataset.bookingStatus);if(error)return toast(error.message,'error');toast('Đã cập nhật trạng thái');await loadBookings();renderDashboard()})}
$('#bookingSearch').oninput=renderBookings;$('#bookingStatusFilter').onchange=renderBookings;
$('#exportBookings').onclick=()=>{const rows=filteredBookings(),cols=['name','phone','booking_date','booking_time','people','duration','note','status','created_at'];const csv=[cols.join(','),...rows.map(r=>cols.map(c=>'"'+String(r[c]??'').replace(/"/g,'""')+'"').join(','))].join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='khoi-room-bookings.csv';a.click();URL.revokeObjectURL(a.href)};


function renderSpaces(){const grid=$('#spaceAdminGrid');if(!grid)return;grid.innerHTML=state.spaces.map(s=>`<article class="space-admin-card"><img src="${esc(s.image_url)}" alt=""><div><label>Thứ tự<input type="number" min="0" value="${Number(s.sort_order||0)}" data-space-sort="${s.id}"></label><label class="space-toggle"><input type="checkbox" ${s.enabled?'checked':''} data-space-enabled="${s.id}"> Hiển thị</label><button class="danger-btn" data-space-delete="${s.id}">Xóa</button></div></article>`).join('')||'<div class="panel">Chưa có ảnh. Upload ảnh đầu tiên để hiển thị trên website.</div>';
  $$('[data-space-sort]').forEach(el=>el.onchange=()=>updateSpace(el.dataset.spaceSort,{sort_order:Number(el.value||0)}));
  $$('[data-space-enabled]').forEach(el=>el.onchange=()=>updateSpace(el.dataset.spaceEnabled,{enabled:el.checked}));
  $$('[data-space-delete]').forEach(el=>el.onclick=()=>deleteSpace(el.dataset.spaceDelete));
}
async function updateSpace(id,payload){const {error}=await db.from('space_gallery').update(payload).eq('id',id);if(error)return toast(error.message,'error');toast('Đã cập nhật ảnh');await loadSpaces()}
async function deleteSpace(id){if(!confirm('Xóa ảnh này khỏi Không gian Khói?'))return;const {error}=await db.from('space_gallery').delete().eq('id',id);if(error)return toast(error.message,'error');toast('Đã xóa ảnh');await loadSpaces()}
$('#spaceImageFile')?.addEventListener('change',async e=>{const files=[...(e.target.files||[])];if(!files.length)return;try{toast('Đang upload ảnh không gian...');let order=state.spaces.reduce((m,x)=>Math.max(m,Number(x.sort_order||0)),0)+1;for(const file of files){const url=await uploadFile(file,'spaces');const {error}=await db.from('space_gallery').insert({image_url:url,enabled:true,sort_order:order++});if(error)throw error}e.target.value='';toast('Đã thêm ảnh không gian');await loadSpaces()}catch(err){toast(err.message||'Upload thất bại','error')}});

function fillPopupForm(){const p=state.popup||{};$('#popupEnabled').checked=Boolean(p.enabled);$('#popupEnabledLabel').textContent=p.enabled?'Đang bật':'Đang tắt';$('#popupTitle').value=p.title||'';$('#popupBody').value=p.body||'';$('#popupCtaLabel').value=p.cta_label||'';$('#popupCtaUrl').value=p.cta_url||'';$('#popupFrequency').value=p.frequency||'session';$('#popupImageUrl').value=p.image_url||'';$('#popupStartAt').value=safeLocalDateTime(p.start_at);$('#popupEndAt').value=safeLocalDateTime(p.end_at);updatePopupPreview()}
function updatePopupPreview(){const src=$('#popupImageUrl').value.trim();$('#popupPreviewImage').src=src||'';if(!src)$('#popupPreviewImage').removeAttribute('src');$('#popupPreviewTitle').textContent=$('#popupTitle').value||'Có gì mới tại Khói?';$('#popupPreviewBody').textContent=$('#popupBody').value||'Nội dung popup sẽ hiển thị ở đây.';$('#popupPreviewButton').textContent=$('#popupCtaLabel').value||'Xem ngay';$('#popupEnabledLabel').textContent=$('#popupEnabled').checked?'Đang bật':'Đang tắt'}
['popupEnabled','popupTitle','popupBody','popupCtaLabel','popupImageUrl'].forEach(id=>$('#'+id).addEventListener('input',updatePopupPreview));$('#popupImageFile').onchange=e=>{const f=e.target.files?.[0];if(f)$('#popupPreviewImage').src=URL.createObjectURL(f)};
$('#popupForm').addEventListener('submit',async e=>{e.preventDefault();try{let image=$('#popupImageUrl').value.trim()||null;const file=$('#popupImageFile').files?.[0];if(file){toast('Đang upload ảnh popup...');image=await uploadFile(file,'popup');$('#popupImageUrl').value=image}const payload={id:1,enabled:$('#popupEnabled').checked,title:$('#popupTitle').value.trim()||'Có gì mới tại Khói?',body:$('#popupBody').value.trim()||null,image_url:image,cta_label:$('#popupCtaLabel').value.trim()||'Xem ngay',cta_url:$('#popupCtaUrl').value.trim()||'#events',frequency:$('#popupFrequency').value,start_at:$('#popupStartAt').value?new Date($('#popupStartAt').value).toISOString():null,end_at:$('#popupEndAt').value?new Date($('#popupEndAt').value).toISOString():null,updated_at:new Date().toISOString()};const {error}=await db.from('site_popup').upsert(payload);if(error)throw error;toast('Đã lưu popup');await loadPopup();renderDashboard()}catch(err){toast(err.message,'error')}});

ensureAuth();
